# Generated by Django 4.1.5 on 2023-01-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_myuser_groups_myuser_is_active_myuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
    ]
